### ISSUE TITLE
"peformance is not defined" error

### ISSUE THREAD

**Issue by rbhalla** [11ty/eleventy#3414]
### Operating system

macOS Sonoma 14.5

### Eleventy

2.0.1

### Describe the bug

I am getting a "performance is not defined error"

```
[11ty] 1. Having trouble rendering liquid template ./README.md (via TemplateContentRenderError)
[11ty] 2. performance is not defined (via ReferenceError)
[11ty]
[11ty] Original error stack trace: ReferenceError: performance is not defined
[11ty]     at new Context (/Users/rbhalla/dev/project/node_modules/liquidjs/dist/liquid.node.cjs.js:2619:74)
[11ty]     at Liquid._render (/Users/rbhalla/dev/project/node_modules/liquidjs/dist/liquid.node.cjs.js:4094:56)
[11ty]     at Liquid.render (/Users/rbhalla/dev/project/node_modules/liquidjs/dist/liquid.node.cjs.js:4098:31)
[11ty]     at /Users/rbhalla/dev/project/node_modules/@11ty/eleventy/src/Engines/Liquid.js:268:21
```

### Reproduction steps

The reproduction steps are outlined in the getting started guide: https://www.11ty.dev/docs/

1. make new directory
2. run
```
echo '<!doctype html><title>Page title</title><p>Hi</p>' > index.html
echo '# Heading' > README.md
```
4. run `npx @11ty/eleventy`
5. See an error

### Expected behavior

No error

### Screenshots

I'm on node v15.10.0

**Comment by uncenter** [comment]
Upgrading to Node.js v16 fixes this error, though I am not sure why this is happening as both Eleventy v2.0.1 and LiquidJS v10.16.1 should support `>= 14` (as per their `package.json` `engines.node` fields).

**Comment by uncenter** [comment]
Looks like you do in fact need to explicitly import the `performance` object pre-Node.js v16 with `const { performance } = require('perf_hooks');`.  Still not sure why the Node.js compatibility is incorrectly reported though!

**Comment by vrugtehagel** [comment]
This issue has been resolved in LiquidJS's just-released version `10.16.2`! Since that's a minor version, it now just magically works. @rbhalla, you might need to re-install your dependencies for it to take effect. Unless you're having further issues then @zachleat can close this issue 🙂

**Comment by rbhalla** [comment]
So unfortunately a reinstall did not work, but I did get a different error!

```
[11ty] Eleventy CLI Fatal Error: (more in DEBUG output)
[11ty] Cannot find module 'node:perf_hooks'
[11ty] Require stack:
[11ty] - /Users/rbhalla/dev/project/node_modules/liquidjs/dist/liquid.node.cjs.js
[11ty] - /Users/rbhalla/dev/project/node_modules/@11ty/eleventy/src/Engines/Liquid.js
[11ty] - /Users/rbhalla/dev/project/node_modules/@11ty/eleventy/src/Plugins/RenderPlugin.js
[11ty] - /Users/rbhalla/dev/project/node_modules/@11ty/eleventy/src/Eleventy.js
[11ty] - /Users/rbhalla/dev/project/node_modules/@11ty/eleventy/cmd.js (via Error)
```

This did make me realise how behind on node versions I was so I've upgraded and it seems to be working well on v22.6.0.

I think I'm happy to close this issue, but I wonder if it's worth updating the site's copy to indicate 14 isn't the minimum version?

**Comment by uncenter** [comment]
> but I wonder if it's worth updating the site's copy to indicate 14 isn't the minimum version?

It should be, there just seems to be another issue with the LiquidJS package.

**Comment by vrugtehagel** [comment]
Huh. I did test this with Node 14, and that works, but for some reason, Node 15 doesn't like the `node:` prefix. I'll look into it again!

I think keeping the minimum version 14 is nice at least until it starts being an bother to support it, though admittedly this is @zachleat's call to make. Personally, I think we can just fix this and leave the 14 on the site.

For what it's worth, yes, please do upgrade your Node version if you can. 14 is pretty darn old by now 😉 

As for closing this issue, yeah, feel free to close it. It's not actually an Eleventy issue anyway; it's a bug in LiquidJS. I'll re-open an issue there.
