### ISSUE TITLE
Regression. eleventyComputed is not merged/executed in the DataCascade

### ISSUE THREAD

**Issue by KajKandler** [11ty/eleventy#3831]
I make use of the eleventyComputed in two places in the data cascade.

In a folder-level data file, I calculate

```
export default {
    // Optional - in a global data file or config
    layout: "layouts/glossary.njk",
    tags: ["glossary"],
    eleventyComputed: {
        first_letter: function (data) { return data.title[0] }
    }
};
```

In the YAML front matter of the template, I calculate
```
eleventyComputed:
  "id": "{{ metadata.url }}glossary/entity/#webpage"
```
The later does not get computed, but stays `"{{ metadata.url }}glossary/entity/#webpage"`, where I'd expect `"https:my.example.com/glossary/entity/#webpage"`

After resetting to 11ty 3.0.0 the behavior works just as expected.

**Comment by zachleat** [comment]
Can you include a minimum viable test case for reproduction? I created one myself but it didn’t exhibit the behavior you described

**Comment by adamstddrd** [comment]
I'm running into this same issue. I have some template front matter that looks like this:
```
eleventyComputed:
  downloads:
  -
    title: "Steady for desktop"
    description: "A fast, focused Steady experience, complete with native notifications."
    links:
    -
      title: "MacOS"
      url: "{{ site.download_link_mac }}"
      button: "Download"
      icon: "icon-apple"
    -
      title: "Windows"
      url: "{{ site.download_link_windows }}"
      button: "Download"
      icon: "icon-windows"
(truncated for brevity)
```

In 11ty 3.1, values like `{{ site.download_link_mac }}` are present in the rendered output. When I downgrade to 11ty 3.0, the values are computed as expected.

**Comment by zachleat** [comment]
@adamstddrd I can confirm your issue (a regression from #3728), though I don’t think it’s related to @KajKandler’s issue. I’ve filed your issue at #3850 — let’s group up over there

**Comment by zachleat** [comment]
Any word here on a test case? I don’t think I’ll be able to move forward without being able to repro

**Comment by KajKandler** [comment]
Sorry for the late reply!

I seem unable to install a barebones 11ty/eleventy@3.1.1 - As soon as I add a eleveny.config.js it fails with `Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/entitygarden/git/eleventy_' imported from /Users/entitygarden/git/eleventy_#3831/node_modules/@11ty/eleventy/src/Util/Require.js`

I suspect it is actually the error in the array. Because I have the issue nested in an array structure. I just simplified for reporting purposes. Yet I'm not too familiar with installing the 3.1.2.beta1 in my environment. On npm I can only get 3.1.1.beta1 as the latest.

Would you mind waiting until this array resolution is published on npm for a final confirmation?

**Comment by zachleat** [comment]
Were you able to retest with v3.1.1 or v3.1.2?

**Comment by KajKandler** [comment]
Sorry, for the late reply. Either 3.1.1 or 3.1.2 fixed it.
