### ISSUE TITLE
Numeric tags in v3.1 cause "tagName.startsWith is not a function (via TypeError)"

### ISSUE THREAD

**Issue by dwoodman2008** [11ty/eleventy#3875]
### Operating system

Windows 10

### Eleventy

v 3.1.1

### Describe the bug

Numeric tags as in 
tags:
  - 2024

give the following error in v 3.1 but work OK in v 3.0

Problem writing Eleventy templates:                                                                                                                        
tagName.startsWith is not a function (via TypeError)                                                                                                       
                                                                                                                                                           
Original error stack trace: TypeError: tagName.startsWith is not a function                                                                                
    at TemplateDepGraph.addTag (file:///M:/myDev24/11stamfordFood2506/node_modules/@11ty/eleventy/src/Util/TemplateDepGraph.js:35:13)                      
    at TemplateDepGraph.addTemplate (file:///M:/myDev24/11stamfordFood2506/node_modules/@11ty/eleventy/src/Util/TemplateDepGraph.js:106:10)                
    at GlobalDependencyMap.addNewNodeRelationships (file:///M:/myDev24/11stamfordFood2506/node_modules/@11ty/eleventy/src/GlobalDependencyMap.js:374:12)   
    at #addEntryToGlobalDependencyGraph (file:///M:/myDev24/11stamfordFood2506/node_modules/@11ty/eleventy/src/TemplateMap.js:120:20)                      
    at TemplateMap.addAllToGlobalDependencyGraph (file:///M:/myDev24/11stamfordFood2506/node_modules/@11ty/eleventy/src/TemplateMap.js:130:41)             
    at TemplateWriter._addToTemplateMap (file:///M:/myDev24/11stamfordFood2506/node_modules/@11ty/eleventy/src/TemplateWriter.js:335:20)                   
    at async TemplateWriter._createTemplateMap (file:///M:/myDev24/11stamfordFood2506/node_modules/@11ty/eleventy/src/TemplateWriter.js:343:3)             
    at async TemplateWriter.generateTemplates (file:///M:/myDev24/11stamfordFood2506/node_modules/@11ty/eleventy/src/TemplateWriter.js:376:3)              
    at async TemplateWriter.write (file:///M:/myDev24/11stamfordFood2506/node_modules/@11ty/eleventy/src/TemplateWriter.js:425:38)                         
    at async Eleventy.executeBuild (file:///M:/myDev24/11stamfordFood2506/node_modules/@11ty/eleventy/src/Eleventy.js:1397:19)             


### Reproduction steps

1. In eleventy-base-blog add following two lines to front matter in secondpost.md

> 2. 

3. See an error

### Expected behavior

Add an error message showing which template causes error.
Add info to collections docs saying whether numeric tags are valid or not

### Reproduction URL

_No response_

### Screenshots

_No response_

**Comment by dwoodman2008** [comment]
Having problems formatting
2 should read 
tags:
 - number 2
 - 2

**Comment by zachleat** [comment]
Shipping with v3.1.2-beta.4 or newer.
