### ISSUE TITLE
Cannot find module '/var/task/eleventy-serverless-map.json'

### ISSUE THREAD

**Issue by quinteno** [11ty/eleventy#2165]
**Describe the bug**
My serverless function works fine in local (using `netlify-cli 8.6.15`), but when deployed to production environment I get the following error when trying to invoke the function:

```
{"errorType":"Error","errorMessage":"Cannot find module '/var/task/eleventy-serverless-map.json'\nRequire stack:\n- /var/task/node_modules/@11ty/eleventy/src/Serverless.js\n- /var/task/node_modules/@11ty/eleventy/src/Eleventy.js\n- /var/task/web/netlify/functions/preview/index.js\n- /var/task/preview.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js","trace":["Error: Cannot find module '/var/task/eleventy-serverless-map.json'","Require stack:","- /var/task/node_modules/@11ty/eleventy/src/Serverless.js","- /var/task/node_modules/@11ty/eleventy/src/Eleventy.js","- /var/task/web/netlify/functions/preview/index.js","- /var/task/preview.js","- /var/runtime/UserFunction.js","- /var/runtime/index.js","    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)","    at Function.Module._load (internal/modules/cjs/loader.js:746:27)","    at Module.require (internal/modules/cjs/loader.js:974:19)","    at require (internal/modules/cjs/helpers.js:93:18)","    at Serverless.getContentMap (/var/task/node_modules/@11ty/eleventy/src/Serverless.js:102:22)","    at Serverless.isServerlessUrl (/var/task/node_modules/@11ty/eleventy/src/Serverless.js:117:27)","    at Runtime.handler (/var/task/web/netlify/functions/preview/index.js:33:14)"]}
```

My serverless function is stored at netlify/functions/preview/index.js. When I run this locally, the necessary `eleventy-serverless-map.json` is generated in the `functionsDir` and everything works as expected.

I was doing some research and came across [this issue](https://github.com/11ty/eleventy/issues/2138) that had a similar error, but their solution didn't fix my problem.

Here is my `netlify.toml` file:

```
[build]
command = "yarn build"
publish = "build"

[functions]
directory = "netlify/functions"

[[redirects]]
from = "/preview/:slug"
to = "/.netlify/functions/preview"
status = 200
force = true
_generated_by_eleventy_serverless = "preview"

[[redirects]]
from = "/preview/"
to = "/.netlify/functions/preview"
status = 200
force = true
_generated_by_eleventy_serverless = "preview"
```

**To Reproduce**
Create an 11ty serverless function locally and deploy it to Netlify. Attempt to invoke the function in production and see error.

**Expected behavior**
Expect to see function executed with access to all automatically generated build files.

**Environment:**

- OS and Version: MacOS Big Sur 11.2.3
- Eleventy Version: 1.0.0-beta.10

**Comment by quinteno** [comment]
After some digging, I believe this could be related to the `getProjectDir()` method inside of `Serverless.js`. If 

```
getProjectDir() {
    // TODO? improve with process.env.LAMBDA_TASK_ROOT—was `/var/task/` on lambda (not local)
    let dir = path.join(this.options.functionsDir, this.name);
    let paths = [
      path.join(TemplatePath.getWorkingDir(), dir), // netlify dev
      path.join("/var/task/src/", dir), // AWS Lambda absolute path  <-- **I THINK THIS IS THE ISSUE**      path.join(TemplatePath.getWorkingDir()), // after the chdir below
    ];

    for (let path of paths) {
      if (fs.existsSync(path)) {
        return path;
      }
    }
```

The error I get complains about not being able to find the serverless map file in `/var/task`. Could it be because its being written to the `/var/task/src/` folder and 11ty or Lambda is looking in the wrong place?

**Comment by quinteno** [comment]
I was finally able to solve this issue by moving my serverless functions folder to the root of the project and pointing my `netlify.toml` to that. The structure of my project has the front-end living in a subdirectory which I don't think Netlify Functions currently support.
