### ISSUE TITLE
Filters in Liquid not working as documented

### ISSUE THREAD

**Issue by forsartis** [11ty/eleventy#504]
In the supported features section of the Liquid docs (https://www.11ty.io/docs/languages/liquid/#supported-features) the syntax for Eleventy Universal Filters doesn’t work.
```html
<ul>
  {% for item in testdata | sort %}
    <li>{{ item }}</li>
  {% endfor %}
</ul>
```
This throws the follwing error:
```
Problem writing Eleventy templates: (more in DEBUG output)
> Having trouble rendering html template ./index.html (TemplateContentRenderError)
> Having trouble compiling template ./index.html (TemplateContentCompileError)
> illegal tag: {% for item in testdata | sort %}, line:11 (ParseError)
> illegal tag: {% for item in testdata | sort %} (AssertionError):
    AssertionError: illegal tag: {% for item in testdata | sort %}
…
```

**Comment by kleinfreund** [comment]
I’m not quite sure if filters are supposed to work on Liquid iteration tags. The following works:

```liquid
<ul>
{% assign testdata = some_array | sort %}
{% for item in testdata %}
  <li>{{ item }}</li>
{% endfor %}
</ul>
```

**Comment by forsartis** [comment]
Ah, good to know filters work on the assign tag. Though they didn’t work inside `{% %}` tags at all, but only tried iteration and if tags.

No examples that use filters on iteration tag as far as I know. It works in Nunjucks, but isn’t supported in Liquid, I guess.

**Comment by zachleat** [comment]
Yeah, I personally found this to be an annoying discrepancy between Nunjucks and Liquid too.

There are a _few_ fancy things you can do in Liquid iteration though. Peep the tests here: https://github.com/harttle/liquidjs/blob/master/test/integration/builtin/tags/for.ts#L176

Hope that’s useful, it was kinda buried.

**Comment by zachleat** [comment]
> This is an automated message to let you know that a helpful response was posted to your issue and for the health of the repository issue tracker the issue will be closed. This is to help alleviate issues hanging open waiting for a response from the original poster.

> If the response works to solve your problem—great! But if you’re still having problems, do not let the issue’s closing deter you if you have additional questions! Post another comment and I will reopen the issue. Thanks!

**Comment by whaleen** [comment]
Having trouble with Liquid's "where" filter (https://liquidjs.com/filters/where.html#sidebar)

Trying:

`{% assign nerd_cards = collections.card | where: "class", "nerd" %}
    
{% for card in nerd_cards %}
  <li>
    {{ card.data.title }}
  </li>
{% endfor %}
`

Resulting in complete unfiltered list of ALL cards... :(

**Comment by pdehaan** [comment]
> Having trouble with Liquid's "where" filter ([liquidjs.com/filters/where.html#sidebar](https://liquidjs.com/filters/where.html#sidebar))

Possibly worth pointing out that it looks like eleventy@0.11.0 shipped with an older version of liquidjs which may not have had `where` filter implemented:
https://github.com/11ty/eleventy/blob/36c5022d885d147b5677fc08ef157eb849b8437a/package.json#L109
(where the `where` filter might not have been added to liquidjs until v8.1.0 ([per the CHANGELOG](https://github.com/harttle/liquidjs/blob/a9d3a5a402ae26b64848f6e0bc85cbb5a386413d/CHANGELOG.md#810-2019-04-02))

The latest Eleventy in GitHub looks like it might have the latest Liquidjs, so you could either try installing from GitHub directly, or the docs has a good section on bringing your own custom version of Liquidjs: https://www.11ty.dev/docs/languages/liquid/#optional-set-your-own-library-instance (if you'd rather try manually npm installing the latest liquidjs and using that directly until a new version of eleventy is released).

**Comment by whaleen** [comment]
Thanks for looking into this @pdehaan 

I've tried my best to attempt both your suggestions. 

Not sure how to use the latest version of Eleventy if it's newer than 0.11.0. I'm only running 'npm install' and getting the latest release. How can I install directly from GitHub? 

And, for the other option, I've tried 'npm install liquidjs' and now am unsure about the instructions (https://www.11ty.dev/docs/languages/liquid/#optional-set-your-own-library-instance) to 'SET YOUR OWN LIBRARY INSTANCE' in the 11ty docs.

How do I make 11ty, presumably in .eleventy.js, to utilise the latest liquidjs I've now got in my package.json:

```
  "dependencies": {
    "liquidjs": "^9.16.1",

```

**Comment by pdehaan** [comment]
@whaleen Probably better to just inject the latest liquidjs instead of installing the bleeding edge from GitHub. See https://github.com/pdehaan/11ty-504

I forgot that the constructor and stuff changed between liquidjs@6 and liquidjs@9 (but thankfully there was a GitHub PR for updating docs https://github.com/11ty/11ty-website/pull/326/files):

1. https://github.com/pdehaan/11ty-504/blob/master/.eleventy.js shows how you can use your custom LiquidJS after running <kbd>npm i liquidjs@latest -D</kbd>.
2. https://github.com/pdehaan/11ty-504/blob/master/src/pages/home.liquid shows how you can use the `where` filter in liquidjs@9 (using some dummy data, I didnt try creating some fake collections to test if your exact use case would work or if there are potential issues w/ nested collection data -- although https://github.com/harttle/liquidjs/issues/178 implies nested data should work in v9.5.0+).

**Comment by anneke** [comment]
@pdehaan hi Peter, thanks for commenting! I have tried your suggestion, unfortunately I get this error. I'm probably not the only one who will come accross this page, so just to let others know, you might get the same issue.
I've installed the latest liquidjs version, but using your code in my eleventy config file I get this:

```
`TemplateContentRenderError` was thrown
> liquidEngine.renderer.renderTemplates(...).then is not a function, file:./content/nl/kitchensink.md, line:33, col:1

`RenderError` was thrown
> liquidEngine.renderer.renderTemplates(...).then is not a function
```

@pdehaan do you have any idea what causes this error? When I remove your code (still having installed a different liquid version), there's no problem. Except for the where filter seemingly not working yet :)

**Comment by anneke** [comment]
Ah, I see using the code on the Eleventy documentation page about this ( https://www.11ty.dev/docs/languages/liquid/#optional-set-your-own-library-instance currently ) does not work for me. I'll open a new issue :)

**Comment by pdehaan** [comment]
OK, looks like liquidjs@9 support was added via #1058 PR. There were a lot more internal changes in that PR than I would have guessed, so it might not currently be possible to shim a newer version of liquid w/ `render` support until 11ty v1.0.0 ships.

It doesn't look like there's an 11ty v1 beta or prerelease on npm yet, per:

```sh
npm info @11ty/eleventy versions --json
[
  "0.2.0",
  "0.2.1",
  # ...,
  "0.11.0-beta.2",
  "0.11.0-beta.3",
  "0.11.0-beta.4",
  "0.11.0",
  "0.11.1"
]
```

Not sure if you'd have any better luck installing via GitHub directly via <kbd>npm i github:11ty/eleventy -S</kbd> (until `eleventy@1.0.0-beta` appears on npm). I haven't used LiquidJS's new `render` tag yet, so I don't have any snippets handy to test locally to see if that'd work or not, I'm just making wild, unfounded guesses. :yolo:

**Comment by pdehaan** [comment]
OK, had a few minutes to mess around with it tonight and installing via the GitHub repo's latest commit (eleventy v1.0.0-beta.0) seems to let me use liquidjs@9 and the `{% render %}` tag without any additional tricks or workarounds.

https://github.com/pdehaan/11ty-liquid9-render

```liquid
{% render header.liquid, name:"peter" %}

<p>Powered by {% calaphon poweredBy.eleventy %}, and {% calaphon poweredBy.liquidjs %}</p>
```

### OUTPUT

```html
<header>
  <p>This is a rendered header</p>
  <p>Author: peter</p>
  <p>Rank: </p>
</header>

<p>Powered by @11ty/eleventy@1.0.0-beta.0, and liquidjs@9.19.0</p>
```

**Comment by anneke** [comment]
In the end I worked around it by adding an Eleventy filter, so instead of 

```
{% assign blogposts = collections.published_posts | where:"locale", "en" %}
```

I can do

```
{% assign blogposts = collections.published_posts | getEnglish %}
```

Which uses this (in eleventy.js):
```
 eleventyConfig.addFilter("getEnglish", function (collection) {
    return collection.filter((post) => Boolean(post.data.locale == "en"));
  });
```

That was good enough for my usecase. I just wanted to leave this here for other googlers like me, updating the version of Liquid would be the cleaner solution of course :)
